import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;

import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;

public class WebAppImg extends javax.swing.JFrame {    

    private int image_height;
    private int image_aspect_ratio;
    private Graphics2D engine;
    private JLabel photoComponent; 
    /**
     * Creates new form WebAppImg
     */
    public WebAppImg() {
        initComponents();
    }
        
    
    JLabel jLabel1 = new javax.swing.JLabel();
    JTextField jTextField1 = new javax.swing.JTextField();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

    	
    	
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 480));
        
        panel = new JPanel();
        
        JPanel panel_1 = new JPanel();
        
        JPanel panel_2 = new JPanel();
        
        JPanel panel_5 = new JPanel();
        
        JLabel lblPatientsName = new JLabel("Patient's Name: ");
        lblPatientsName.setFont(new Font("Leelawadee UI Semilight", Font.PLAIN, 20));
        panel_5.add(lblPatientsName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(panel_1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        				.addComponent(panel_2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        				.addComponent(panel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        				.addComponent(panel_5, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 570, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(panel_5, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(panel_1, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(panel_2, GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        			.addContainerGap())
        );
        
        textField_2 = new JTextField();
        textField_2.setFont(new Font("Leelawadee UI Semilight", Font.PLAIN, 17));
        panel_5.add(textField_2);
        textField_2.setColumns(20);
        GridBagLayout gbl_panel_2 = new GridBagLayout();
        gbl_panel_2.columnWidths = new int[]{139, 278, 153, 0};
        gbl_panel_2.rowHeights = new int[]{15, 58, 38, 0};
        gbl_panel_2.columnWeights = new double[]{1.0, 0.0, 0.0, Double.MIN_VALUE};
        gbl_panel_2.rowWeights = new double[]{0.0, 1.0, 0.0, Double.MIN_VALUE};
        panel_2.setLayout(gbl_panel_2);
        
        JLabel lblNewLabel_1 = new JLabel("Write your caption here");
        lblNewLabel_1.setFont(new Font("Leelawadee UI Semilight", Font.PLAIN, 16));
        GridBagConstraints gbc_lblNewLabel_1 = new GridBagConstraints();
        gbc_lblNewLabel_1.anchor = GridBagConstraints.SOUTH;
        gbc_lblNewLabel_1.insets = new Insets(0, 0, 5, 5);
        gbc_lblNewLabel_1.gridx = 1;
        gbc_lblNewLabel_1.gridy = 0;
        panel_2.add(lblNewLabel_1, gbc_lblNewLabel_1);
        
        textField = new JTextField();
        textField.setFont(new Font("Leelawadee UI Semilight", Font.PLAIN, 14));
        GridBagConstraints gbc_textField = new GridBagConstraints();
        gbc_textField.insets = new Insets(0, 0, 5, 5);
        gbc_textField.fill = GridBagConstraints.BOTH;
        gbc_textField.gridx = 1;
        gbc_textField.gridy = 1;
        panel_2.add(textField, gbc_textField);
        textField.setColumns(10);
        
        JPanel panel_7 = new JPanel();
        GridBagConstraints gbc_panel_7 = new GridBagConstraints();
        gbc_panel_7.insets = new Insets(0, 0, 0, 5);
        gbc_panel_7.fill = GridBagConstraints.BOTH;
        gbc_panel_7.gridx = 1;
        gbc_panel_7.gridy = 2;
        panel_2.add(panel_7, gbc_panel_7);
        
        JButton btnPost = new JButton();
        btnPost.setText("Post");
        btnPost.setFont(new Font("Leelawadee UI Semilight", Font.PLAIN, 15));
        panel_7.add(btnPost);
                GridBagLayout gbl_panel_1 = new GridBagLayout();
                gbl_panel_1.columnWidths = new int[]{85, 403, 85, 0};
                gbl_panel_1.rowHeights = new int[]{168, 30, 30, 0};
                gbl_panel_1.columnWeights = new double[]{1.0, 1.0, 0.0, Double.MIN_VALUE};
                gbl_panel_1.rowWeights = new double[]{1.0, 0.0, 0.0, Double.MIN_VALUE};
                panel_1.setLayout(gbl_panel_1);
                
                JPanel panel_6 = new JPanel();
                GridBagConstraints gbc_panel_6 = new GridBagConstraints();
                gbc_panel_6.insets = new Insets(0, 0, 5, 5);
                gbc_panel_6.fill = GridBagConstraints.BOTH;
                gbc_panel_6.gridx = 1;
                gbc_panel_6.gridy = 0;
                panel_1.add(panel_6, gbc_panel_6);
                
                JLabel lblNewLabel_2 = new JLabel("\"Display Picture Here\"");
                lblNewLabel_2.setFont(new Font("Leelawadee UI Semilight", Font.PLAIN, 14));
                panel_6.add(lblNewLabel_2);
                
                JPanel panel_3 = new JPanel();
                GridBagConstraints gbc_panel_3 = new GridBagConstraints();
                gbc_panel_3.insets = new Insets(0, 0, 5, 5);
                gbc_panel_3.fill = GridBagConstraints.BOTH;
                gbc_panel_3.gridx = 1;
                gbc_panel_3.gridy = 1;
                panel_1.add(panel_3, gbc_panel_3);
                
                 JButton jButton1 = new javax.swing.JButton();
                jButton1.setFont(new Font("Leelawadee UI Semilight", Font.PLAIN, 15));
                jButton1.setText("Browse");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });
                panel_3.add(jButton1);
                
                JPanel panel_4 = new JPanel();
                GridBagConstraints gbc_panel_4 = new GridBagConstraints();
                gbc_panel_4.insets = new Insets(0, 0, 0, 5);
                gbc_panel_4.fill = GridBagConstraints.BOTH;
                gbc_panel_4.gridx = 1;
                gbc_panel_4.gridy = 2;
                panel_1.add(panel_4, gbc_panel_4);
                
                
               
                jTextField1.setColumns(20);
                jTextField1.setFont(new Font("Leelawadee UI Semilight", Font.PLAIN, 14));
                panel_4.add(jTextField1);
                jTextField1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jTextField1ActionPerformed(evt);
                    }
                });
        
        JLabel lblNewLabel = new JLabel("Create a Post");
        lblNewLabel.setFont(new Font("Leelawadee UI Semilight", Font.PLAIN, 20));
        panel.add(lblNewLabel);
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        jTextField1.setText(filename);
        try {
            ImageIcon ii= new ImageIcon(scaleImage(120, 120, ImageIO.read(new File(f.getAbsolutePath()))));//get the image from file chooser and scale it to match JLabel size
            jLabel1.setIcon(ii);
            System.out.println(f.getAbsolutePath());
            System.out.println(jTextField1.getText());
            System.out.println(textField.getText());
            System.out.println(textField_2.getText());
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public static BufferedImage scaleImage(int w, int h, BufferedImage img) throws Exception {
        BufferedImage bi;
        bi = new BufferedImage(w, h, BufferedImage.TRANSLUCENT);
        Graphics2D g2d = (Graphics2D) bi.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
        g2d.drawImage(img, 0, 0, w, h, null);
        g2d.dispose();
        return bi;
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WebAppImg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WebAppImg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WebAppImg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WebAppImg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WebAppImg().setVisible(true);
            }
        });
        //Create a file chooser

    }
    private JPanel panel;
    private JTextField textField;
    private JTextField textField_1;
    private JTextField textField_2;
}